name: Build Windows DLL

on:
  push:
    branches: [ "build-v3.21.12" ]

env:
  PYTHON_VERSION: '3.10'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  build-windows:
    strategy:
      matrix:
        windows: [windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.windows }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Dependencies
        run: git submodule update --init --recursive
      - name: Build
        run: |
          mkdir solution && cd solution
          cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=.\binary -Dprotobuf_BUILD_SHARED_LIBS=ON ..
          cmake --build ./ --config Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nodejs-windows-artifacts
          path: |
            solution/Release
